### PR TITLE
Clean dependencies

### PR DESCRIPTION
**Pull request by erikkemperman**
@Tcharl @jdubois
Hope you don't mind -- I took the liberty of cleaning this up a bit (well, IMHO anyway :-).

I've tried to make topical, self-explanatory commits so you can hopefully follow my reasoning, and discard any if you don't agree.

To check if things work as planned, I've used this in a fork of the server-lib, here:
https://github.com/erikkemperman/jhipster/tree/jhipster-deps

Please let me know if you think this is going in the right direction.

@Tcharl You were working on making a PR to the generator repo about using these dependencies, right?

EDIT just to avoid misunderstandings, this is on top of https://github.com/jhipster/jhipster-dependencies/pull/1 !

### CODE REVIEW

**Comment by Tcharl** [comment]
Hi Eric,

I'm not totally for removing 'duplicates' properties: I think that this is a good practice to use that 'duplicate' pattern everytime, let's take a simple hypothetic example
`<org.springframework.version>5.0.0</org.springframework.version>
<org.springframework_spring-beans.version>${/org.springframework.version}</org.springframework_spring-beans.version>
<org.springframework_spring-aop.version>${/org.springframework.version}</org.springframework_spring-aop.version>
`

Using this pattern gives us much flexibility and is based on convention:
* All the 'real' asset dependencies have the same property pattern: <groupId>_<artifactId>.version, so that it can then be parseable by a mojo, a third party tool (stats, monitoring, etc). This remark is also valid for plugins versions properties, ... This capacity is very helpful when dealing with big maven confs
* That pattern allows to have a 'no brainer' strategy while using these properties within children poms (I don't have to review and search within the pom holding that property to be able to consume it
* In case of 'regression' of an asset version, I can use the previous version of that artifact without impacting the other (if org.springframework.version is promoted to 5.0.1, I can easily keep the spring-aop version to 5.0.0 if there's a problem in that newer version).
* Prefixing dependency properties by groupId is useful in many case: for example, to ensure the difference when using the osgified version of the jars instead/in parallel of the original one, e.g. org.apache.servicemix.bundles_guava vs guava.

So yes, my version is a little more verbose, but as it brings some added value and ease the maintenance ...

**Comment by erikkemperman** [comment]
Hi Charlie,

Thanks for taking a look at my proposal!

About the duplicate properties: personally I think we should only split them in the cases where we actually want _different_ versions of related dependencies. Otherwise I think it is slightly cleaner to de-duplicate, in the same way that e.g. spring-boot-dependencies does it:

https://github.com/spring-projects/spring-boot/blob/v1.5.7.RELEASE/spring-boot-dependencies/pom.xml

But it's not a really big deal for me -- so if you and/or @jdubois feel strongly that we want to keep these duplicates I will happily amend my PR.

Did you agree with the other suggesions?

**Comment by jdubois** [comment]
By default I wouldn't duplicate properties - but at the moment I don't have enough time to review this, so I don't have a strong opinion here. I'm sorry, I don't know when I will have enough free time for this, and as it's a very important design decision I need to have that time.

**Comment by erikkemperman** [comment]
@jdubois Thanks Julien! I think that reviewing this properly will also require a concrete PR for generator-jhipster to demonstrate how this new module would fit in. I'm not sure if @Tcharl is working on that, but I think so. Otherwise I might take a look this week.

But until we consider any changes to generator-jhipster, there is basically zero impact to what we change here. So I would argue we can just merge in what "looks good" superficially and then get to more thorough review and fixes when we attempt conjoining with the generator?

**Comment by jdubois** [comment]
Oh yes sorry I didn't see this was on the `jhipster/jhipster-dependencies` - let me merge those PRs!

**Comment by erikkemperman** [comment]
@Tcharl Forgot to react to your last point about including groupIds with the property names -- I really think we should stick with the conventions of spring-boot here, for example if we want to override a dependency (like we do with [assertj](https://github.com/spring-projects/spring-boot/blob/v1.5.7.RELEASE/spring-boot-dependencies/pom.xml#L52)) we only have to redefine the property, and don't have to repeating the whole dependency block.

The case you mention where you want to have alternative implementations of e.g. guava _side-by-side_ at the same time seems very unlikely to me -- and even if it does happen, I propose we use the main one (especially if it also is defined in `spring-boot-dependencies`) without groupId and just add a prefix for the alternate.

Does that make sense?

**Comment by erikkemperman** [comment]
@jdubois Thanks for merging, but I think this happened in the wrong order?

Perhaps I should have made more clear that my PR (#2) was ON TOP OF @Tcharl's PR (#1). So now you've merged his branch into master, and then subsequently my branch into his.

In other words, there are still commits in the onlydependencies branch which I would love to see in master...

Apologies, maybe such meta-PRs are not a very good approach :-)

**Comment by jdubois** [comment]
Sorry I merged them in order.... I also added the license, etc

**Comment by erikkemperman** [comment]
No worries, I will rebase and make a new PR!

**Comment by jdubois** [comment]
OK, be careful I also applied our code format on the project, so it's consistent with the rest of JHipster

**Comment by erikkemperman** [comment]
I did the same in my branch (indentation). I think I can just cherry-pick my commits except that one...

**Comment by erikkemperman** [comment]
Done, #3.

**Comment by Tcharl** [comment]
The only convention spring-boot-dependencies has is that it does not have conventions, and I really dislike this: whenever I use spring poms has parent, I'm keeping them opened in a tab everytime in order to have a property label or a plugin execution, and I find this really weird. Sticking to Maven conventions (groupId for a container, artifactId for nodes) seems natural to me and really helped maintenance of my projects.

**Comment by erikkemperman** [comment]
@Tcharl We're still talking about property names, right?

Regardless of whether one likes the conventions in spring-boot-dependencies, the _technical_ consequence of using something like
```xml
<org.assertj_assertj-core.version>3.6.2</org.assertj_assertj-core.version>
```

Is that we would also have to duplicate the whole `<dependency>...</dependency>` block just to override the version string.

Instead, if we use the same property names as the parent spring-boot-dependencies where possible, we only have to override the prop. So in this case simply the following is enough:
```xml
<assertj.version>3.6.2</assertj.version>
```

**Comment by Tcharl** [comment]
Good catch! You've got a point on this ;-)

**Pull request merged**
