### PR TITLE
upgrade spring-platform to Brussels-SR6

### PR DESCRIPTION
**Pull request by DanielFran**
See https://spring.io/blog/2017/11/29/spring-io-platform-brussels-sr6

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@PierreBesson 
Prepare upgrade to spring-boot 1.5.9 https://github.com/jhipster/generator-jhipster/issues/6755

**Comment by erikkemperman** [comment]
FYI it looks like the Travis build fails for the couchbase sample. Unfortunately don't have time to look into that at the moment.

**Comment by DanielFran** [comment]
Was not able to test Couchbase myself, but not shure how changes can impact it!

**Comment by erikkemperman** [comment]
Me neither, and could be something wrong with my local setup I guess.

**Pull request merged**
