### PR TITLE
Fine tuning

### PR DESCRIPTION
**Pull request by erikkemperman**
@jdubois Just these couple of little changes, and then I'll be very close to submitting the main change in generator-jhipster. Could I ask you to release these as 0.0.3, so I can amend my PRs against the latest?

Sorry to be taking up so much of your time these last couple of days ;-)

### CODE REVIEW

**Comment by erikkemperman** [comment]
By the way, this repo has a .travis.yml, but PRs are not currently being tested. Maybe still need to enable this new aritfact on travis-ci.org?

**Comment by jdubois** [comment]
@erikkemperman yes I just enabled Travis

**Comment by jdubois** [comment]
Version v0.0.3 is being sync to Maven Central, it can take up to 2 hours

**Comment by erikkemperman** [comment]
Thanks Julien!

**Pull request merged**
