### PR TITLE
Bump jhipster server lib to 1.1.13

### PR DESCRIPTION
**Pull request by erikkemperman**
Need this to rebase the PR on generator-jhipster.

### CODE REVIEW

**Comment by erikkemperman** [comment]
Actually, @jdubois would you consider a PR that puts jhipster-dependencies and jhipster server lib in a single repository, for simultaneous release cycle? The co-dependency is troublesome, I think. For instance now I'd like to bump jhipster-server lib managed dependency to 1.1.13 here, but then to be really clean the server lib would have to get the latest jhipster-dependencies, and so on :-)

**Comment by jdubois** [comment]
I'm not sure they should have the same release cycle - indeed you probably want `jhipster/jhipster-dependencies` to follow the `jhipster/jhipster` versions, but not the other way around, and also sometimes we do intermediary releases for test or patch purposes. I'm fine with having them separated for the moment. My biggest concern is having something simple, that I can merge as soon as our OIDC support is out, and then we can work on improving it.

**Comment by erikkemperman** [comment]
So, if I understand correctly, you are saying that jhipster-dependencies should be updated for each release of jhipster, but not the other way around?

But that will mean that, for the common case that jhipster-dependencies is released due to an upgraded dependency X to version Y+1, that downstream modules like jhipster-registry and newly generated apps will get X at version Y+1 while being linked against the server lib that was compiled with X at version Y...

That seems like asking for trouble to me :-)

Honestly I don't think a single repository setup is that much more complicated than things are now, and test/patch releases should be fine too as long as we are careful about not consuming those in the main branches of downstream repos (but that is also true currently).

Anyway, obviously I defer to your expertise -- and sorry if I misunderstand your reasoning here!

**Comment by erikkemperman** [comment]
@jdubois I will mark my single-repo PR "on hold" but feel free to close it if you like. 

Thanks for merging the bump in jhipster server lib here. If I could please have a new release, then I can rebase my other PRs without regressing the server lib version... Much appreciated, and sincere apologies to take up so much of your time!

**Comment by jdubois** [comment]
@erikkemperman I just want something simple for the moment, we have so many opened tickets and PRs, I just can't follow everything.
I'm doing the JHipster lib release, no problem!

**Comment by jdubois** [comment]
@erikkemperman sorry, I meant the jhipster-dependencies release - it's on its way to Maven Central!

**Comment by erikkemperman** [comment]
@jdubois No worries, I've been having a little free time lately, but of course I completely understand if it's too much all at once.

Thanks for release, will update my PRs as soon as it hits Maven central!

**Pull request merged**
