### PR TITLE
https://github.com/jhipster/generator-jhipster/issues/6061 Impelment BOM project

### PR DESCRIPTION
**Pull request by Tcharl**
Here's the bom without the parent pom.

Regards,

### CODE REVIEW

**Comment by erikkemperman** [comment]
@Tcharl This looks good! I have a few little ideas about this, would you mind if I try to make a PR onto your `onlydependencies` branch? I think it will be quicker to do it with code than try to explain in an issue :-)

**Comment by erikkemperman** [comment]
@Tcharl Side question, you wanted to eventually add some maven-release-plugin configuration to jhipster, right? Would that mean that all the artifacts have to be moved into a single repository? Or have you found some way around the limitations of the plugin in that regard?

**Comment by Tcharl** [comment]
It seems to me that as long as you configure the scm and site informations on the children poms (the server modules), you don't have to squash them all on a single repo. But I can be wrong on that

**Comment by erikkemperman** [comment]
I got into a lot of trouble once with this -- but the difference is possibly in that case, we wanted to run maven-release-plugin once to release a whole bunch of modules at the same time.

The problem there was that the plugin wants to do some commits, e.g. to bump the `<version>` elements, and that doesn't work across git repository boundaries. So we ended up making a single repository with all the modules as (regular) subdirectories.

I think this isn't an issue if the plan is to keep releasing these artifacts more or less independently.

**Comment by Tcharl** [comment]
IMO, keeping module in separate repository is synonym to have a separate module lifecycle. Otherwise we would prefer keep them in the same place (as it's easier to manage).

**Pull request merged**
